import { readFileSync, writeFileSync } from 'node:fs'

import { createAnimationCoverageReport } from '../src/grappling/animationRecipes/coverage.ts'

interface RuntimeDataset {
  readonly positional_transitions: readonly {
    readonly id: string
    readonly display_name: string
    readonly source_position: string
    readonly destination_position: string
  }[]
}

const datasetUrl = new URL('../../data/generated/simroll_bjj_mvp.normalized.json', import.meta.url)
const outputUrl = new URL('../../docs/animation-coverage.md', import.meta.url)
const dataset = JSON.parse(readFileSync(datasetUrl, 'utf8')) as RuntimeDataset
const report = createAnimationCoverageReport(dataset.positional_transitions.map((transition) => ({
  id: transition.id,
  name: transition.display_name,
  sourcePositionId: transition.source_position,
  destinationPositionId: transition.destination_position,
})))

const lines = [
  '# Animation Coverage',
  '',
  '<!-- Generated by `npm.cmd run animation:coverage`; do not edit manually. -->',
  '',
  `- Total: ${report.total}`,
  `- Explicit: ${report.explicit}`,
  `- Family: ${report.family}`,
  `- Fallback: ${report.fallback}`,
  `- Constraint-enhanced: ${report.constraintEnhanced}`,
  '',
  '## Constraint-enhanced transitions',
  '',
  ...report.transitions
    .filter(({ constraintEnhanced }) => constraintEnhanced)
    .map((entry) => `- \`${entry.id}\` (${entry.sourcePositionId} â†’ ${entry.destinationPositionId})${entry.familyId ? ` â€” \`${entry.familyId}\`` : ''}`),
  '',
  '## Explicit transitions',
  '',
  ...report.transitions
    .filter(({ coverage }) => coverage === 'explicit')
    .map((entry) => `- \`${entry.id}\` (${entry.sourcePositionId} → ${entry.destinationPositionId})`),
  '',
  '## Family-backed transitions',
  '',
  ...report.transitions
    .filter(({ coverage }) => coverage === 'family')
    .map((entry) => `- \`${entry.id}\` (${entry.sourcePositionId} → ${entry.destinationPositionId}) — \`${entry.familyId}\``),
  '',
  '## Fallback transitions',
  '',
  ...report.transitions
    .filter(({ coverage }) => coverage === 'fallback')
    .map((entry) => `- \`${entry.id}\` (${entry.sourcePositionId} → ${entry.destinationPositionId})`),
  '',
]
const content = lines.join('\n')

if (process.argv.includes('--check')) {
  let current = ''
  try {
    current = readFileSync(outputUrl, 'utf8')
  } catch {
    // The comparison below emits the same actionable freshness error.
  }
  if (current !== content) {
    throw new Error('Animation coverage report is stale; run npm.cmd run animation:coverage')
  }
  console.log(`Animation coverage is current: ${report.total} total, ${report.explicit} explicit, ${report.family} family, ${report.fallback} fallback, ${report.constraintEnhanced} constraint-enhanced`)
} else {
  writeFileSync(outputUrl, content)
  console.log(`Wrote ${outputUrl.pathname}: ${report.total} total, ${report.explicit} explicit, ${report.family} family, ${report.fallback} fallback, ${report.constraintEnhanced} constraint-enhanced`)
}
